export const INITIALIZE_REALM = 'INITIALIZE_REALM'
export const INITIALIZE_REALM_SUCCESS = 'INITIALIZE_REALM_SUCCESS'
export const INITIALIZE_REALM_FAILURE = 'INITIALIZE_REALM_FAILURE'

export const GET_REALM_INSTANCE = 'GET_REALM_INSTANCE'
export const GET_REALM_INSTANCE_SUCCESS = 'GET_REALM_INSTANCE_SUCCESS'
export const GET_REALM_INSTANCE_FAILURE = 'GET_REALM_INSTANCE_FAILURE'

export const FETCH_PRODUCTS = 'FETCH_PRODUCTS'
export const FETCH_PRODUCTS_SUCCESS = 'FETCH_PRODUCTS_SUCCESS'
export const FETCH_PRODUCTS_FAILURE = 'FETCH_PRODUCTS_FAILURE'